# Generated by Django 4.2.28 on 2026-02-25 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('title', models.JSONField(default=dict, help_text='i18n: {"en": "...", "ar": "..."}')),
                ('description', models.JSONField(default=dict)),
                ('icon_url', models.URLField(blank=True)),
                ('difficulty_level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Concept',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('title', models.JSONField(default=dict)),
                ('description', models.JSONField(default=dict)),
                ('order', models.PositiveIntegerField(default=0)),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='concepts', to='tracks.track')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('track', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('title', models.JSONField(default=dict)),
                ('description', models.JSONField(default=dict)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='easy', max_length=10)),
                ('instructions', models.JSONField(default=dict)),
                ('starter_code', models.JSONField(default=dict, help_text='Keyed by language: {"python": "...", "javascript": "..."}')),
                ('test_code', models.JSONField(default=dict)),
                ('solution', models.JSONField(default=dict)),
                ('order', models.PositiveIntegerField(default=0)),
                ('concept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='tracks.concept')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('concept', 'slug')},
            },
        ),
    ]
