# Generated by Django 4.2.28 on 2026-03-08 08:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('kids_curriculum', '0001_initial'),
        ('kids_profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KidStreak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_streak', models.PositiveIntegerField(default=0)),
                ('longest_streak', models.PositiveIntegerField(default=0)),
                ('last_activity_date', models.DateField(blank=True, null=True)),
                ('kid', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='streak', to='kids_profiles.kidprofile')),
            ],
        ),
        migrations.CreateModel(
            name='KidProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.BooleanField(default=False)),
                ('workspace_json', models.JSONField(blank=True, default=dict, help_text='Saved Blockly workspace state')),
                ('points_earned', models.PositiveIntegerField(default=0)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('time_spent_seconds', models.PositiveIntegerField(default=0)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='kids_curriculum.kidchallenge')),
                ('kid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='kids_profiles.kidprofile')),
            ],
            options={
                'ordering': ['-updated_at'],
                'unique_together': {('kid', 'challenge')},
            },
        ),
        migrations.CreateModel(
            name='KidAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('badge_type', models.CharField(choices=[('first_code', 'First Code! 🎉'), ('streak_3', '3-Day Streak 🔥'), ('streak_7', 'Week Warrior 💪'), ('streak_30', 'Monthly Master 🏆'), ('points_100', 'Century Club 💯'), ('points_500', 'Super Coder ⚡'), ('points_1000', 'Code Legend 🌟'), ('all_easy', 'Easy Peasy 🌈'), ('all_medium', 'Challenge Accepted 🎯'), ('first_game', 'Game Maker 🎮'), ('first_animation', 'Animator 🎬'), ('helper', 'Helpful Friend 🤝'), ('speed_demon', 'Speed Coder ⏱️'), ('perfect_score', 'Perfectionist ✨')], max_length=30)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('icon_emoji', models.CharField(default='🏅', max_length=10)),
                ('earned_at', models.DateTimeField(auto_now_add=True)),
                ('kid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to='kids_profiles.kidprofile')),
            ],
            options={
                'ordering': ['-earned_at'],
                'unique_together': {('kid', 'badge_type')},
            },
        ),
    ]
