# Generated by Django 4.2.28 on 2026-02-25 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='assignmentsubmission',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='assignment',
            name='answer_type',
            field=models.CharField(choices=[('essay', 'Written Essay'), ('document', 'Document Upload (PDF/DOCX)'), ('code_python', 'Python Code'), ('code_javascript', 'JavaScript Code'), ('code_any', 'Code (Any Language)'), ('project_url', 'Project URL (GitHub/CodePen)'), ('file_any', 'Any File'), ('mixed', 'Multiple Formats Accepted')], default='essay', max_length=20),
        ),
        migrations.AddField(
            model_name='assignment',
            name='auto_grade',
            field=models.BooleanField(default=False, help_text='If True, run test_code against submission'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='max_attempts',
            field=models.PositiveIntegerField(default=1, help_text='How many times a student can submit'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='programming_language',
            field=models.CharField(blank=True, help_text='e.g. python, javascript, typescript', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='assignment',
            name='rubric',
            field=models.TextField(blank=True, help_text='Grading rubric/criteria description'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='starter_code',
            field=models.TextField(blank=True, help_text='Pre-filled code template for code assignments'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='test_code',
            field=models.TextField(blank=True, help_text='Automated tests to run against code submissions'),
        ),
        migrations.AddField(
            model_name='assignmentsubmission',
            name='attempt_number',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='assignmentsubmission',
            name='auto_grade_result',
            field=models.JSONField(blank=True, help_text='Automated test results', null=True),
        ),
        migrations.AddField(
            model_name='assignmentsubmission',
            name='code_content',
            field=models.TextField(blank=True, help_text='For code submissions'),
        ),
        migrations.AddField(
            model_name='assignmentsubmission',
            name='code_language',
            field=models.CharField(blank=True, help_text='Language of submitted code', max_length=50),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='submission_type',
            field=models.CharField(choices=[('text', 'Text/Essay'), ('file_upload', 'File Upload'), ('code', 'Code'), ('url', 'URL/Link'), ('mixed', 'Multiple Types')], default='text', max_length=20),
        ),
    ]
