# Generated by Django 4.2.28 on 2026-03-08 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='account_type',
            field=models.CharField(choices=[('standard', 'Standard'), ('kid', 'Kid'), ('parent', 'Parent'), ('teacher', 'Teacher')], default='standard', max_length=20),
        ),
    ]
