# Generated by Django 4.2.28 on 2026-02-26 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform_name', models.CharField(default='Wayne LMS', max_length=100)),
                ('tagline', models.CharField(default='Learn to code', max_length=255)),
                ('support_email', models.EmailField(default='support@wayne-lms.example.com', max_length=254)),
                ('timezone', models.CharField(default='Asia/Dubai', max_length=50)),
                ('default_language', models.CharField(default='en', max_length=5)),
                ('maintenance_mode', models.BooleanField(default=False)),
                ('logo_url', models.URLField(blank=True)),
                ('favicon_url', models.URLField(blank=True)),
                ('primary_color', models.CharField(default='#F97316', max_length=7)),
                ('custom_css', models.TextField(blank=True)),
                ('stripe_enabled', models.BooleanField(default=False)),
                ('stripe_public_key', models.CharField(blank=True, max_length=255)),
                ('stripe_secret_key', models.CharField(blank=True, max_length=255)),
                ('paypal_enabled', models.BooleanField(default=False)),
                ('paypal_client_id', models.CharField(blank=True, max_length=255)),
                ('paypal_secret', models.CharField(blank=True, max_length=255)),
                ('default_currency', models.CharField(default='USD', max_length=3)),
                ('email_provider', models.CharField(choices=[('ses', 'AWS SES'), ('smtp', 'SMTP')], default='ses', max_length=10)),
                ('smtp_host', models.CharField(blank=True, max_length=255)),
                ('smtp_port', models.IntegerField(default=587)),
                ('smtp_username', models.CharField(blank=True, max_length=255)),
                ('smtp_password', models.CharField(blank=True, max_length=255)),
                ('smtp_encryption', models.CharField(choices=[('tls', 'TLS'), ('ssl', 'SSL')], default='tls', max_length=5)),
                ('ses_region', models.CharField(blank=True, max_length=30)),
                ('ses_access_key', models.CharField(blank=True, max_length=255)),
                ('ses_secret_key', models.CharField(blank=True, max_length=255)),
                ('from_name', models.CharField(default='Wayne LMS', max_length=100)),
                ('from_email', models.EmailField(default='noreply@wayne-lms.example.com', max_length=254)),
                ('meta_title', models.CharField(default='Wayne LMS - Learn to Code', max_length=255)),
                ('meta_description', models.TextField(default='Online coding platform')),
                ('og_image_url', models.URLField(blank=True)),
                ('google_analytics_id', models.CharField(blank=True, max_length=50)),
                ('facebook_pixel_id', models.CharField(blank=True, max_length=50)),
                ('mailchimp_api_key', models.CharField(blank=True, max_length=255)),
                ('zapier_webhook_url', models.URLField(blank=True)),
                ('slack_webhook_url', models.URLField(blank=True)),
            ],
            options={
                'verbose_name': 'Platform Settings',
                'verbose_name_plural': 'Platform Settings',
            },
        ),
    ]
