# Generated by Django 4.2.28 on 2026-03-08 08:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KidCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('age_group', models.CharField(choices=[('5-7', 'Ages 5-7'), ('8-10', 'Ages 8-10'), ('11-13', 'Ages 11-13')], default='8-10', max_length=10)),
                ('thumbnail', models.URLField(blank=True)),
                ('icon_emoji', models.CharField(default='🚀', max_length=10)),
                ('color', models.CharField(default='#F97316', max_length=7)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=20)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='KidLesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField()),
                ('description', models.TextField(blank=True)),
                ('intro_text', models.TextField(blank=True, help_text='Kid-friendly intro shown before the challenge')),
                ('order', models.PositiveIntegerField(default=0)),
                ('icon_emoji', models.CharField(default='📝', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='kids_curriculum.kidcourse')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('course', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='KidChallenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField()),
                ('description', models.TextField(blank=True)),
                ('instructions', models.TextField(help_text='Step-by-step kid-friendly instructions')),
                ('difficulty', models.CharField(choices=[('easy', 'Easy ⭐'), ('medium', 'Medium ⭐⭐'), ('hard', 'Hard ⭐⭐⭐')], default='easy', max_length=10)),
                ('challenge_type', models.CharField(choices=[('blocks', 'Block Coding'), ('puzzle', 'Puzzle'), ('animation', 'Animation'), ('game', 'Game Building'), ('art', 'Creative Art')], default='blocks', max_length=20)),
                ('points', models.PositiveIntegerField(default=10)),
                ('order', models.PositiveIntegerField(default=0)),
                ('icon_emoji', models.CharField(default='🎯', max_length=10)),
                ('starter_workspace_json', models.JSONField(blank=True, default=dict, help_text='Initial Blockly workspace')),
                ('toolbox_json', models.JSONField(blank=True, default=dict, help_text='Available blocks for this challenge')),
                ('solution_workspace_json', models.JSONField(blank=True, default=dict, help_text='Solution workspace')),
                ('stage_config', models.JSONField(blank=True, default=dict, help_text='PixiJS stage setup: sprites, background, etc.')),
                ('expected_output', models.JSONField(blank=True, default=dict, help_text='Expected result for validation')),
                ('hints', models.JSONField(blank=True, default=list, help_text='Array of hint strings')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenges', to='kids_curriculum.kidlesson')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('lesson', 'slug')},
            },
        ),
    ]
