# Generated by Django 4.2.28 on 2026-02-25 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500)),
                ('is_correct', models.BooleanField(default=False)),
                ('image_url', models.URLField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('title', models.JSONField(default=dict)),
                ('description', models.JSONField(default=dict)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('is_free', models.BooleanField(default=True)),
                ('thumbnail', models.URLField(blank=True)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('duration', models.PositiveIntegerField(default=0, help_text='Duration in minutes')),
                ('level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', max_length=20)),
                ('what_youll_learn', models.JSONField(blank=True, default=list)),
                ('who_should_take', models.JSONField(blank=True, default=dict)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('enable_certificates', models.BooleanField(default=True)),
                ('enable_discussions', models.BooleanField(default=True)),
                ('enable_drip', models.BooleanField(default=False)),
                ('enable_points', models.BooleanField(default=False)),
                ('enable_live_streams', models.BooleanField(default=False)),
                ('enable_group_purchase', models.BooleanField(default=False)),
                ('enable_quizzes', models.BooleanField(default=True)),
                ('drip_enabled', models.BooleanField(default=False)),
                ('drip_type', models.CharField(blank=True, choices=[('sequential', 'Sequential'), ('scheduled', 'Scheduled'), ('timed', 'Timed')], default='sequential', max_length=20)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrolled_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('progress_percent', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.JSONField(default=dict)),
                ('content', models.JSONField(default=dict)),
                ('lesson_type', models.CharField(choices=[('video', 'Video'), ('text', 'Text'), ('quiz', 'Quiz'), ('exercise', 'Exercise'), ('slides', 'Slides'), ('stream', 'Stream')], default='text', max_length=10)),
                ('video_url', models.URLField(blank=True)),
                ('video_source', models.CharField(blank=True, choices=[('youtube', 'YouTube'), ('vimeo', 'Vimeo'), ('mp4', 'MP4'), ('embed', 'Embed')], max_length=20)),
                ('video_duration', models.CharField(blank=True, help_text='e.g. 3m 42s', max_length=20)),
                ('duration', models.PositiveIntegerField(default=0, help_text='Duration in minutes')),
                ('order', models.PositiveIntegerField(default=0)),
                ('slides_data', models.JSONField(blank=True, default=list, help_text='Array of {title, content, image_url}')),
                ('stream_url', models.URLField(blank=True)),
                ('stream_platform', models.CharField(blank=True, choices=[('youtube', 'YouTube'), ('vimeo', 'Vimeo'), ('zoom', 'Zoom')], max_length=20)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('is_live', models.BooleanField(default=False)),
                ('recording_url', models.URLField(blank=True)),
                ('drip_date', models.DateTimeField(blank=True, null=True)),
                ('drip_days_after_enrollment', models.IntegerField(blank=True, null=True)),
                ('requires_previous', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='LessonComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='LessonProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.JSONField(default=dict)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('question_type', models.CharField(choices=[('single_choice', 'Single Choice'), ('multi_choice', 'Multiple Choice'), ('true_false', 'True/False'), ('fill_blank', 'Fill in the Blank'), ('keyword_match', 'Keyword Match'), ('image_match', 'Image Match')], default='single_choice', max_length=20)),
                ('order', models.PositiveIntegerField(default=0)),
                ('explanation', models.TextField(blank=True)),
                ('image_url', models.URLField(blank=True)),
                ('correct_text', models.CharField(blank=True, help_text='For fill_blank/keyword_match', max_length=500)),
                ('points', models.PositiveIntegerField(default=1)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.JSONField(default=dict)),
                ('quiz_type', models.CharField(choices=[('module_quiz', 'Module Quiz'), ('assessment', 'Assessment')], default='module_quiz', max_length=20)),
                ('questions_count', models.PositiveIntegerField(default=0)),
                ('order', models.PositiveIntegerField(default=0)),
                ('time_limit', models.PositiveIntegerField(blank=True, help_text='Time limit in minutes', null=True)),
                ('passing_grade', models.PositiveIntegerField(default=50, help_text='Passing grade percentage')),
                ('max_retakes', models.PositiveIntegerField(blank=True, help_text='Null = unlimited', null=True)),
                ('randomize_questions', models.BooleanField(default=False)),
                ('show_correct_answers', models.BooleanField(default=True)),
                ('points_per_question', models.PositiveIntegerField(default=1)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='QuizAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_answer', models.CharField(blank=True, max_length=500)),
                ('is_correct', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='QuizAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('score', models.PositiveIntegerField(default=0)),
                ('total_questions', models.PositiveIntegerField(default=0)),
                ('passed', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlisted_by', to='courses.course')),
            ],
        ),
    ]
