# Generated by Django 4.2.28 on 2026-02-25 14:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0003_course_enable_assignments_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField()),
                ('description', models.TextField(blank=True)),
                ('icon_url', models.CharField(blank=True, max_length=500)),
                ('criteria_type', models.CharField(choices=[('first_exercise', 'First Exercise'), ('all_easy', 'All Easy'), ('all_medium', 'All Medium'), ('all_hard', 'All Hard'), ('all_exercises', 'All Exercises'), ('streak_5', '5 Streak'), ('concept_complete', 'Concept Complete'), ('perfect_score', 'Perfect Score')], max_length=30)),
                ('criteria_value', models.PositiveIntegerField(blank=True, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='badges', to='courses.course')),
            ],
            options={
                'unique_together': {('course', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='CourseConcept',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('slug', models.SlugField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('icon', models.CharField(blank=True, max_length=50, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='concepts', to='courses.course')),
                ('prerequisites', models.ManyToManyField(blank=True, related_name='dependents', to='courses.courseconcept')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('course', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='CourseExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField()),
                ('description', models.TextField(blank=True)),
                ('instructions', models.TextField()),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='easy', max_length=10)),
                ('starter_code', models.TextField(blank=True)),
                ('test_code', models.TextField(blank=True)),
                ('solution', models.TextField(blank=True)),
                ('language', models.CharField(choices=[('python', 'Python'), ('javascript', 'JavaScript'), ('typescript', 'TypeScript')], default='python', max_length=20)),
                ('points', models.PositiveIntegerField(default=10)),
                ('order', models.PositiveIntegerField(default=0)),
                ('concept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='courses.courseconcept')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='courses.course')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('course', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='UserCourseBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('earned_at', models.DateTimeField(auto_now_add=True)),
                ('course_badge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='earned_by', to='courses.coursebadge')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_badges', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'course_badge')},
            },
        ),
        migrations.CreateModel(
            name='CourseExerciseProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed')], default='not_started', max_length=20)),
                ('code_submitted', models.TextField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('points_earned', models.PositiveIntegerField(default=0)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('course_exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='courses.courseexercise')),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercise_progress', to='courses.enrollment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercise_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'course_exercise')},
            },
        ),
    ]
