# Generated by Django 4.2.28 on 2026-02-25 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_coursebadge_courseconcept_courseexercise_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='lesson_type',
            field=models.CharField(choices=[('video', 'Video'), ('text', 'Text'), ('quiz', 'Quiz'), ('exercise', 'Exercise'), ('slides', 'Slides'), ('stream', 'Stream'), ('assignment', 'Assignment')], default='text', max_length=10),
        ),
    ]
