# Generated by Django 4.2.28 on 2026-02-26 03:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_alter_lesson_lesson_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='certificate_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='course',
            name='giftable',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='course',
            name='layout_template',
            field=models.CharField(default='default', max_length=20),
        ),
        migrations.CreateModel(
            name='DripSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drip_type', models.CharField(choices=[('days_after_enrollment', 'Days After Enrollment'), ('specific_date', 'Specific Date'), ('after_previous', 'After Previous Module')], max_length=25)),
                ('days_after', models.IntegerField(default=0)),
                ('specific_date', models.DateField(blank=True, null=True)),
                ('enabled', models.BooleanField(default=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drip_schedules', to='courses.course')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.module')),
            ],
        ),
        migrations.CreateModel(
            name='CourseNotice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notices', to='courses.course')),
            ],
        ),
        migrations.CreateModel(
            name='CourseFAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('answer', models.TextField()),
                ('order', models.IntegerField(default=0)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='courses.course')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
