# Generated by Django 4.2.29 on 2026-04-04 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_alter_course_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='enable_practice',
            field=models.BooleanField(default=False, help_text='Enable practice exercises section for this course'),
        ),
    ]
