# Generated by Django 4.2.29 on 2026-04-05 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_add_enable_practice'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_type',
            field=models.CharField(choices=[('standard', 'Standard'), ('industry', 'Industry Implementation')], default='standard', max_length=20),
        ),
        migrations.AddField(
            model_name='course',
            name='industry_meta',
            field=models.JSONField(blank=True, default=dict, help_text='For industry courses: {target_roles, workflows, tools, deliverables, roi_benefits}'),
        ),
    ]
