# Generated by Django 4.2.28 on 2026-02-25 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PointConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('registered', 'Registered'), ('course_purchased', 'Course Purchased'), ('quiz_passed', 'Quiz Passed'), ('quiz_perfect', 'Quiz Perfect Score'), ('lesson_completed', 'Lesson Completed'), ('certificate_earned', 'Certificate Earned'), ('group_joined', 'Group Joined')], max_length=30, unique=True)),
                ('points_awarded', models.PositiveIntegerField(default=10)),
                ('point_name', models.CharField(default='coins', max_length=50)),
                ('point_rate', models.FloatField(default=0.01, help_text='Dollar value per point')),
            ],
        ),
        migrations.CreateModel(
            name='PointTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=30)),
                ('points', models.IntegerField()),
                ('description', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserPoints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_points', models.PositiveIntegerField(default=0)),
                ('redeemed_points', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
