# Generated by Django 4.2.28 on 2026-02-25 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bundles', '0001_initial'),
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bundle',
            name='courses',
            field=models.ManyToManyField(blank=True, related_name='bundles', to='courses.course'),
        ),
    ]
