# Generated by Django 4.2.28 on 2026-02-26 03:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('type', models.CharField(choices=[('percentage', 'Percentage'), ('fixed', 'Fixed Amount'), ('free', 'Free')], max_length=20)),
                ('value', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('usage_limit', models.IntegerField(default=100)),
                ('used_count', models.IntegerField(default=0)),
                ('valid_from', models.DateTimeField()),
                ('valid_to', models.DateTimeField()),
                ('min_purchase', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('scope', models.CharField(choices=[('all', 'All Courses'), ('selected', 'Selected Courses'), ('bundles', 'Bundles')], default='all', max_length=20)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SmartCouponConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coupon_type', models.CharField(choices=[('birthday', 'Birthday'), ('welcome', 'Welcome'), ('referral', 'Referral'), ('abandoned_cart', 'Abandoned Cart')], max_length=30, unique=True)),
                ('enabled', models.BooleanField(default=False)),
                ('discount_percentage', models.IntegerField(default=10)),
                ('extra_config', models.JSONField(blank=True, default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='CouponUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('used_at', models.DateTimeField(auto_now_add=True)),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usages', to='coupons.coupon')),
            ],
        ),
    ]
